### PR TITLE
Create ty.json

### PR DESCRIPTION
**Pull request by schenkty**

### CODE REVIEW

**Comment by Joohansson** [comment]
Your sponsor link is not valid, please leave blank and add back later if you have submitted github sponsorship request and still waiting

**Comment by schenkty** [comment]
@Joohansson Please review again - the link should now be active.

**Comment by schenkty** [comment]
I am going to withdraw my PR given the comments regarding Vybe. I don't believe it is fair to suggest that I can't use projects that I work on to provide context. I should not have to censor myself because I work on multiple projects; I hope you reconsider your hostility for future developers who contribute their time to Nano based projects.

**Comment by Joohansson** [comment]
You are welcome back the day you can prove you are doing development on the Nano platform and not being hostile yourself. It's stated on the front page.

**Pull request closed without merging**
